### ISSUE TITLE
While running the back-up logs the same does ends into error

### ISSUE THREAD

**Issue by KC078** [IvoVermeer/cpi-logs#1]
Error:
(node:20612) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded

Can you please let me know what is the limitation on size?

**Comment by IvoVermeer** [comment]
Hi KC708,

Do you have more information, can you put the entire call-stack information either on https://pastebin.com/ or in a gist please? 

Maximum call stack size refers to a program issue, not to a file size.

EDIT: Please also ention where you get the error: In the console where you started the app, or in the browser.

**Comment by KC078** [comment]
Hello Ivo,
Tried reproducing again, the issue is no more occurring.
You can resolve this issue if i see any problems using the app will open a new issue
Thanks for the quick reply
Regards,
KC

**Comment by KC078** [comment]
Issue not reproducible

**Comment by IvoVermeer** [comment]
Hi KC,

That's odd. Please let me know if and when the issue pops up again and make sure to grab a copy of the stack trace. I went through the code yesterday and I couldn't spot any obvious causes. I'll do some tests too.

Thanks again!
